import styles from './layout.module.css'

export const metadata = {
  title: '¿Cómo funciona el pico y placa?',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <main className={styles.main}>
      <div className={styles.content}>
        {children}
      </div>
    </main>
  )
}
